### ISSUE TITLE
[BUG] [error] Configuration - SSL connect error (UnknownException)

### ISSUE THREAD

**Issue by nzkller** [henrywhitaker3/Speedtest-Tracker#611] opened 2021-05-26 11:32 UTC
**Describe the bug**
While trying to run the container returns the following 

`root@26ccf54f5063:/# php /config/www/artisan speedtest:version`
`Speedtest Tracker v1.10.4`
`root@26ccf54f5063:/# php /config/www/artisan speedtest:run`
`Running speedtest, this might take a while...`
`[2021-05-26 07:23:32.639] [error] Configuration - SSL connect error (UnknownException)`
`[2021-05-26 07:23:32.640] [error] Configuration - Cannot retrieve configuration document (0)`
`[2021-05-26 07:23:32.640] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)`
`[2021-05-26 07:23:32.640] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)`
`{"type":"log","timestamp":"2021-05-26T11:23:32Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}`
`Something went wrong running the speedtest.`
`root@26ccf54f5063:/# php /config/www/artisan speedtest:latest`
`Last speedtest run at: 2021-05-26 11:23:32 (manual)`
`Speedtest failed`

Also got the following

[2021-05-26 07:22:03.646] [warning] Failure during HTTP request (effective url: https://cli.speedtest.net/api/cli/config?deviceId=7d6cb496be9a84db5ef842fafeefa90db5153fdb08c309e8950d26e497380bf6&hid=VS%2505QSV%2503SV%2504%2506%2503&sid=d357d0a60b46494182c81b6d1a9a1a7ea79e91c9554ed67b00a807226267386e&uname=Linux%205.4.0-1035-raspi%20%2338-Ubuntu%20SMP%20PREEMPT%20Tue%20Apr%2020%2021%3A37%3A03%20UTC%202021%20aarch64)
[2021-05-26 07:22:03.646] [warning] UnknownException
[2021-05-26 07:22:03.647] [warning] SSL connect error

**To Reproduce**
1. Go to the WebGUI try to run the test and it fails, CLI it fails as well.
2. On the CLI you can run

php /config/www/artisan speedtest:version
php /config/www/artisan speedtest:run
php /config/www/artisan speedtest:latest

**Expected behavior**
The SSL connect should be successful to retrieve the setting.json and the speediest to run

**Context**

Docker version 20.10.6, build 370c289
Linux 5.4.0-1035-raspi #38-Ubuntu SMP PREEMPT Tue Apr 20 21:37:03 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
Speedtest-Tracker Version: v1.10.4
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0] on linux
Using DockStarter latest version

Thanks in advance and best regards

**Comment by henrywhitaker3** [comment] 2021-05-26 12:16
Dupe of #583 ?

**Comment by nzkller** [comment] 2021-05-26 12:49
> Dupe of #583 ?
Hi @henrywhitaker3 

I already checked the older issues. and I found the CA certificates on the raspberry PI 

openssl version -d
OPENSSLDIR: "/usr/lib/ssl"

openssl  s_client  -connect  cli.speedtest.net:443
CONNECTED(00000003)
depth=2 OU = GlobalSign Root CA - R3, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign Atlas R3 DV TLS CA 2020
verify return:1
depth=0 CN = *.cdnst.net
verify return:1

Certificate chain
 0 s:CN = *.cdnst.net
   i:C = BE, O = GlobalSign nv-sa, CN = GlobalSign Atlas R3 DV TLS CA 2020
 1 s:C = BE, O = GlobalSign nv-sa, CN = GlobalSign Atlas R3 DV TLS CA 2020
   i:OU = GlobalSign Root CA - R3, O = GlobalSign, CN = GlobalSign

Server certificate
-----BEGIN CERTIFICATE-----
Z/C1NC8k0F2RWWB5fTgxTpNM1m0kyAg3u6JM8hQwKGIBRtIqEZdfAg==
-----END CERTIFICATE-----
subject=CN = *.cdnst.net

issuer=C = BE, O = GlobalSign nv-sa, CN = GlobalSign Atlas R3 DV TLS CA 2020

No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits

SSL handshake has read 3822 bytes and written 394 bytes
Verification: OK

New, TLSv1.2, Cipher is ECDHE-RSA-CHACHA20-POLY1305
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-CHACHA20-POLY1305
    Session-ID: 78BBEE28BC400CA094CDF138EAC7245AEC0D1FFE01030EA0671E74D115765AF6
    Session-ID-ctx:
    Master-Key: 79EDAC84700AF75E34E57C2AB6E5515A9A423A477EC016CAE9635DF080833F440159C6FFFE7817578436746D35BBB39C
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 3f 88 e0 7a 45 92 8f ad-6f ac f8 d6 42 19 d9 a5   ?..zE...o...B...
    0010 - 8b cb 86 c9 2f 94 8a d9-ae c9 1e bf a9 3a be ca   ..../........:..
    0020 - cc a9 f1 18 f8 e1 7c 7d-81 24 cd 4f 15 1d c0 cc   ......|}.$.O....
    0030 - 80 4c d1 3d b1 20 fe a4-4f c7 ef 90 b1 5b 43 1e   .L.=. ..O....[C.
    0040 - 30 0d 4a 87 16 ce 3c 50-d8 5f 28 99 06 bf 8a 41   0.J...<P._(....A
    0050 - 11 c4 96 a5 56 99 0d 54-88 a5 3d 39 e0 f2 50 31   ....V..T..=9..P1
    0060 - 29 9e 2b c5 86 0c b9 d2-02 cb 88 c8 a8 29 ad c1   ).+..........)..
    0070 - d3 90 0b 7a 26 1b 2f 3a-3c 9b c8 9d 6c 00 70 5d   ...z&./:<...l.p]
    0080 - 8d e2 b9 1c ed 94 81 b1-35 c8 4f dc 53 7c b5 79   ........5.O.S|.y
    0090 - 0f 65 37 c5 79 7f f1 dd-7a 44 cf a5 5d ec 81 dc   .e7.y...zD..]...
    00a0 - c7 6c 3a 8c e8 21 a8 1a-19 a1 7f 92 ad 52 6c f2   .l:..!.......Rl.
    00b0 - 28 c6 40 f8 a8 14 83 47-94 44 5f f5 72 3e 41 83   (.@....G.D_.r>A.

   Start Time: 1622032306
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes

And I found the CA inside the folder 

ls /usr/lib/ssl/certs | grep GlobalSign
GlobalSign_ECC_Root_CA_-_R4.pem
GlobalSign_ECC_Root_CA_-_R5.pem
GlobalSign_Root_CA.pem
GlobalSign_Root_CA_-_R2.pem
GlobalSign_Root_CA_-_R3.pem
GlobalSign_Root_CA_-_R6.pem

I'm a bit lost, I have being troubleshooting for days now.

network works fine, im on the latest version of docker and my compose file looks like this

version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker:latest-arm
        ports:
            - 8765:80
        volumes:
            - /home/cdassy/config/speedtest-tracker:/config
        environment:
            - TZ=America/Montreal
            - PGID=1001
            - PUID=1001
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped

**Comment by nzkller** [comment] 2021-05-26 13:04
I just saw that the MAC desktop version got updated sooner than the engine.

https://docs.docker.com/engine/release-notes/

https://docs.docker.com/docker-for-mac/release-notes/

**Comment by nzkller** [comment] 2021-05-26 14:46
I also just got the idea of running the binary of speediest in the host instead of the container and I got the same error, like even worse now, because I have no clue where to start

speedtest -v
[2021-05-26 14:45:58.578] [warning] Failure during HTTP request (effective url: https://cli.speedtest.net/api/cli/config?deviceId=25657b46a2430c147c210c1857e3ffc6c4f878c6a1de924d5d7bbbc53ef6e6d2&hid=%250BF%251AKYO%250C%2507URZ&sid=f909cd3bb7902c86ef9e95f289b28dd0256eb8e299fffb1e3f831e0902d7bd65&uname=Linux%205.4.0-1035-raspi%20%2338-Ubuntu%20SMP%20PREEMPT%20Tue%20Apr%2020%2021%3A37%3A03%20UTC%202021%20aarch64)
[2021-05-26 14:45:58.578] [warning] UnknownException
[2021-05-26 14:45:58.578] [warning] SSL connect error
[2021-05-26 14:45:58.578] [error] Configuration - SSL connect error (UnknownException)
[2021-05-26 14:45:58.578] [error] Configuration - Cannot retrieve configuration document (0)
[2021-05-26 14:45:58.579] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
[2021-05-26 14:45:58.579] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
[error] Configuration - Could not retrieve or read configuration (ConfigurationError)

**Comment by nzkller** [comment] 2021-06-01 01:15
Hello,

I found the issue and it’s not related to docker or the host or the container.

I have a firewall that is doing SSL decryption and inspection and this was braking the handshake.

Remove the inspection fo the destination cli.speedtest.com fixed the issue.

Sorry for the trouble.

Best regards,

CD

**Closed** 2023-04-12 15:35 UTC
Labels: bug
