### ISSUE TITLE
[Feature Request] Exclude speedtest servers

### ISSUE THREAD

**Issue by OhjeezwhathaveIdone** [henrywhitaker3/Speedtest-Tracker#390] opened 2020-11-24 19:15 UTC
**Describe the feature**
Currently there's an option to have Speedtest-Tracker select from a list of servers, the opposite would be beneficial, exclude servers so that these servers are not used to query the speed.

**Additional context**
From the limited use I have thus far I'm seeing a few outliers that are skewing true results.  These servers are generally closer to me in location but not by network.

**Comment by henrywhitaker3** [comment] 2020-11-24 23:15
This is a duplicate of #354, so I'm going to close this.

The cli by Ookla that this project uses only supports specifying a server id to use, and doesn't have an option to exclude servers. I would suggest gathering a list of the IDs of servers that don't skew the results and whitelisting those server ids

**Closed** 2020-11-24 23:15 UTC
Labels: enhancement
