### ISSUE TITLE
sh: /Volumes/Web/local/net/Speedtest-Tracker/app/Bin/speedtest: No such file or directory

### ISSUE THREAD

**Issue by jinming88** [henrywhitaker3/Speedtest-Tracker#208] opened 2020-07-28 00:24 UTC
HI. Thanks for your code.
When I install code I got this error.
sh: /Volumes/Web/local/net/Speedtest-Tracker/app/Bin/speedtest: No such file or directory

Please let me know why this happened.
Thanks

**Comment by henrywhitaker3** [comment] 2020-07-28 00:37
Yeah I need to update the manual installation instructions, you need to download [this](https://www.speedtest.net/apps/cli) and put the binary in the Bin directory. I haven't actually tested a manual install with this new binary (have only tested docker) so there may be some permissions issues with it.

**Comment by jinming88** [comment] 2020-07-28 01:02
Great.
Actually, I am not sure yet.
Would you like to let me know after you update code?
I really like your code and features.
Thanks

**Comment by henrywhitaker3** [comment] 2020-07-30 14:10
Yeah I'll update the docs tomorrow and comment back here when it's done

**Comment by VossenTech** [comment] 2020-07-31 20:48
The binary also seems to be missing from the docker image, has been removed from the github files and the link you provided for the binary downloads from speedtest.net doesn't allow for any actual downloading (also unsure which version would be required for the docker image).  Any thoughts on another way to get the binary file?

**Comment by henrywhitaker3** [comment] 2020-07-31 21:01
The docker image should download it on start if it's missing from your volume

**Comment by VossenTech** [comment] 2020-07-31 21:17
Looks like its caused by the same issue as the manual downloads:

Ookla GDPR and EULA accepted. Downloading Speedtest CLI.,
Connecting to bintray.com (108.168.194.93:443),
Connecting to dl.bintray.com (35.161.162.245:443),
wget: server returned error: HTTP/1.1 403 Forbidden,

I guess ill just try it again tomorrow and hope they have their issues resolved by then.

**Comment by henrywhitaker3** [comment] 2020-07-31 21:44
Yeah a 403 seems like an issue on ookla's side of things. So far I'm not including their binary in the image as the EULA says you cannot distribute it.

**Comment by VossenTech** [comment] 2020-08-01 16:13
Well that's a pretty good reason not to include it I suppose. Looks like ookla has resolved their issues for now, a recreate of the container fixed this issue this morning.

**Comment by henrywhitaker3** [comment] 2020-08-03 11:26
@jinming88 have a look at the instructions [here](https://github.com/henrywhitaker3/Speedtest-Tracker/wiki/Manual-Installation). As I have updated the code a bit, you will need to re-download any source files again to make sure they are up to date with the instructions.

**Comment by jinming88** [comment] 2020-08-04 02:11
Okay I will check it

**Comment by henrywhitaker3** [comment] 2020-08-16 10:01
Closing due to no response. Feel free to comment back if it's still not working and I'll re-open the issue

**Closed by henrywhitaker3** 2020-08-16 10:01 UTC
Labels: bug
