### ISSUE TITLE
When BASE_PATH is set, the app never loads [BUG]

### ISSUE THREAD

**Issue by lmarianski** [henrywhitaker3/Speedtest-Tracker#207] opened 2020-07-27 18:44 UTC
**Describe the bug**
When BASE_PATH is set, the app never loads.

**To Reproduce**
Steps to reproduce the behaviour:
1. docker-compose.yml
```yaml
version: "3.2"
services:
  speedtest:
    image: henrywhitaker3/speedtest-tracker
    container_name: speedtest
    ports:
      - 8765:80
    volumes: 
      - ./speedtest:/config
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
      - OOKLA_EULA_GDPR=true
      - BASE_PATH=/speedtest      
    restart: unless-stopped
```
2. Open `http://localhost:8765/speedtest`
3. Watch loading screen forever

**Expected behaviour**
The app to load

**Context**
 - OS: Docker
 - Speedtest-Tracker Version: latest `henrywhitaker3/speedtest-tracker` image

**Comment by henrywhitaker3** [comment] 2020-07-27 19:11
Missing the trailing slash on the URL. Try `http://localhost:8765/speedtest/` (pretty sure this is a duplicate of #175)

**Comment by lmarianski** [comment] 2020-07-27 20:52
Thank you! Can you please make it so `http://localhost:8765/speedtest` works too? (To avoid confusion), a redirect in Nginx would probably be the easiest solution

**Closed** 2020-07-27 21:18 UTC
Labels: bug
