### ISSUE TITLE
[Feature Request] Custom healthchecks.io server

### ISSUE THREAD

**Issue by Nonobis** [henrywhitaker3/Speedtest-Tracker#404] opened 2020-12-08 09:02 UTC
**Describe the feature**
In healthchecks.io settings, please add a simple textbox for a custom server.
By default, textbox should be completed with official server url.

I prefer to use a selfhosted instance for most service. ^_^

Thanks You

Great work !

**Comment by henrywhitaker3** [comment] 2020-12-20 00:17
Duplicate of #324

**Closed by henrywhitaker3** 2020-12-20 00:17 UTC
Labels: enhancement
